/// Flutter icons MarkdownIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MarkdownIcon
///      fonts:
///       - asset: fonts/MarkdownIcon.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///

library markdown_icon;

import 'package:flutter/widgets.dart';

class MarkdownIcon {
  MarkdownIcon._();

  static const _kFontFam = 'MarkdownIcon';
  static const String? _kFontPkg = null;

  static const IconData markdown = IconData(0xf306, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
